### ISSUE TITLE
When there are multiple pages of comments in the article, an error occurs.

### ISSUE THREAD

**Issue by efast1568** [waterholeforum/core#13]
### Bug description

An error occurs when browsing through multiple pages of comments, and there is a chance that editing the comments cannot be executed.

![image](https://github.com/waterholeforum/core/assets/105265831/ff19b392-8478-4088-986c-a9bfe2ddb01b)

![image](https://github.com/waterholeforum/core/assets/105265831/2f3740f0-3bcb-4c9f-a88e-d00d22d86598)

```
`default-d06c0baa.js:24  Uncaught (in promise) DOMException: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
    at https://waterhole.subarist.net/storage/js/default-d06c0baa.js:24:463877
    at new Promise (<anonymous>)
    at F (https://waterhole.subarist.net/storage/js/default-d06c0baa.js:24:463846)
    at oe (https://waterhole.subarist.net/storage/js/default-d06c0baa.js:24:466627)
    at https://waterhole.subarist.net/storage/js/default-d06c0baa.js:24:469312
    at Array.map (<anonymous>)
    at https://waterhole.subarist.net/storage/js/default-d06c0baa.js:24:469304
    at pe (https://waterhole.subarist.net/storage/js/default-d06c0baa.js:24:469345)
(匿名) @ default-d06c0baa.js:24
F @ default-d06c0baa.js:24
oe @ default-d06c0baa.js:24
(匿名) @ default-d06c0baa.js:24
(匿名) @ default-d06c0baa.js:24
pe @ default-d06c0baa.js:24
await in pe (非同步)
_init @ default-d06c0baa.js:24
await in _init (非同步)
he @ default-d06c0baa.js:24
_dbCreate @ default-d06c0baa.js:24
(匿名) @ default-d06c0baa.js:24
Promise.then (非同步)
_dbFlush @ default-d06c0baa.js:24
Jt @ default-d06c0baa.js:24
replaceCurrentPermanentElementWithClone @ default-d06c0baa.js:1
leave @ default-d06c0baa.js:1
preservingPermanentElements @ default-d06c0baa.js:1
await in preservingPermanentElements (非同步)
preservingPermanentElements @ default-d06c0baa.js:1
replaceBody @ default-d06c0baa.js:15
render @ default-d06c0baa.js:15
renderSnapshot @ default-d06c0baa.js:1
render @ default-d06c0baa.js:1
await in render (非同步)
renderPage @ default-d06c0baa.js:15
(匿名) @ default-d06c0baa.js:15
render @ default-d06c0baa.js:15
await in render (非同步)
loadResponse @ default-d06c0baa.js:15
visitRequestCompleted @ default-d06c0baa.js:15
recordResponse @ default-d06c0baa.js:15
requestSucceededWithResponse @ default-d06c0baa.js:15
await in requestSucceededWithResponse (非同步)
receive @ default-d06c0baa.js:1
perform @ default-d06c0baa.js:1
await in perform (非同步)
issueRequest @ default-d06c0baa.js:15
visitStarted @ default-d06c0baa.js:15
start @ default-d06c0baa.js:15
startVisit @ default-d06c0baa.js:15
visitProposedToLocation @ default-d06c0baa.js:15
visitProposedToLocation @ default-d06c0baa.js:15
proposeVisit @ default-d06c0baa.js:15
visit @ default-d06c0baa.js:15
followedLinkToLocation @ default-d06c0baa.js:15
K.clickBubbled @ default-d06c0baa.js:1
`
```

### Steps to reproduce

N/A

### Logs

```shell
N/A
```

### Environment

```yaml
N/A
```

**Comment by tobyzerner** [comment]
Thanks for the report @efast1568. It would be helpful if you could follow the bug report template in the future, as **steps to reproduce** are relevant here, as is your **environment** (browser version).

I was able to reproduce this error but only after playing around for a while. Steps for reproduction are:

1. Log in (this error only occurs while logged in)
2. Navigate to a post with multiple pages of comments
3. Click between pages in the pagination bar to trigger the error

The error is related to the `<emoji-picker>` element present in the comment text editor (hence why it only occurs while logged in). I have reported a bug upstream: https://github.com/nolanlawson/emoji-picker-element/issues/329

> chance that editing the comments cannot be executed

Not sure what you mean here, but I haven't been able to reproduce this part, and it's unlikely that the console error is related.
